### ISSUE TITLE
Struggling to extract packages

### ISSUE THREAD

**Issue by alextrical** [dzervas/fusion360-streamer#5]
I have tried to download and extract the files by both the GUI and CLI, and had a error that prevented completion.

the command line version when run as the following `~/Downloads/fusion360-streamer-linux -p win -o ~/Downloads/Fusion360 -d -e` failed with the following error
```
.....
Downloading package d89b6ec30576ec5c3f357527ca8aa8e04fc1b9d0.tar.xz
Extracting package baf58980ef576109b2022dc95869f9c0240b3a0d.tar.xz
Traceback (most recent call last):
  File "tarfile.py", line 1761, in xzopen
  File "tarfile.py", line 1682, in taropen
  File "tarfile.py", line 1542, in __init__
  File "tarfile.py", line 2377, in next
  File "tarfile.py", line 2350, in next
  File "tarfile.py", line 1122, in fromtarfile
  File "lzma.py", line 200, in read 
  File "_compression.py", line 68, in readinto
  File "_compression.py", line 103, in read
_lzma.LZMAError: Input format not supported by decoder

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "fusion360_streamer/__main__.py", line 69, in <module>
  File "fusion360_streamer/__main__.py", line 56, in main
  File "fusion360_streamer/application.py", line 166, in extract
  File "fusion360_streamer/package.py", line 95, in extract
  File "tarfile.py", line 1652, in open
  File "tarfile.py", line 1765, in xzopen
tarfile.ReadError: not an lzma file
[22088] Failed to execute script '__main__' due to unhandled exception!
```

please can you advise if im missing something obvious, or in need of any specific dependences on Fedora 37

Kind regards

**Comment by dzervas** [comment]
This is related to https://github.com/dzervas/fusion360-streamer/issues/4#issuecomment-1500813979

**Comment by dzervas** [comment]
@alextrical it was a stupid mistake... Can you please check again? I was downloading the wrong URLs so what I saved was actually 403 pages -.-
